### ISSUE TITLE
UART not stable

### ISSUE THREAD

**Issue by sylefeb** [sylefeb/Silice#117]
UART is not stable on ULX3S, recheck.

**Comment by rob-ng15** [comment]
HI,

On PAWS and j1eforth this does seem to be stable, but I run the UART
input/output through buffers. The important bit was checking that the
buffer wasn't full. Maybe missing a check that the UART isn't sending, and
therefore missing characters.

Rob.

**Comment by sylefeb** [comment]
Fixed in 6fbdf9c663615919a0a4b3cfde294052482ea833
This was indeed due to uart_sender triggering again before previous was completed.
