### ISSUE TITLE
README.md and learn-silice/Guidelines.md reference the now-missing docs/silice.pdf ( possibly moved to learn-silice/Documentation.md? )

### ISSUE THREAD

**Issue by d-c-d** [sylefeb/Silice#128]
README.md says "docs contains the LateX documentation sources, and pre-generated documentation pdf"

learn-silice/Guidelines.md also refers to ../docs/silice.pdf

I appears that the contents of the pdf seem to show up in learn-silice/Documentation.md 
Is that where it was moved?

Looks like that was the intention of commit f96b76fe01de379d152fe7133c4fde0b5621fbcf
    "documentation as markdown file"

**Comment by sylefeb** [comment]
Hi, yes - thanks for pointing this out, fixing asap!

**Comment by sylefeb** [comment]
Fixed!
