### ISSUE TITLE
Error building DRAFT

### ISSUE THREAD

**Issue by rob-ng15** [sylefeb/Silice#173]
In file included from /home/rob/Development/github/Silice/src/Utils.cpp:26:
/home/rob/Development/github/Silice/src/Utils.h: In constructor ‘Silice::Utils::LanguageError::LanguageError(int, antlr4::Token*, antlr4::misc::Interval, const char*, ...)’:
/home/rob/Development/github/Silice/src/Utils.h:89:9: error: ‘vsprintf_s’ was not declared in this scope
   89 |         vsprintf_s(m_Message, e_MessageBufferSize, msg, args);
      |         ^~~~~~~~~~
/home/rob/Development/github/Silice/src/Utils.h:89:9: note: the macro ‘vsprintf_s’ had not yet been defined

Above error was generated after pulling Silice from DRAFT branch this morning.

**Comment by sylefeb** [comment]
Thanks for the report! This is fixed in latest draft.
