### ISSUE TITLE
Enhancement Request: Import 16 bit binary files

### ISSUE THREAD

**Issue by rob-ng15** [sylefeb/Silice#210]
When including a file that is 16 bit it has to be included as:

    // RISC-V FAST BRAM and BIOS
    bram uint16 ram[16384] = {
        $include('ROM/BIOS.inc')
        , pad(uninitialized)
    };

with 16bit hex entries.

Binary imports are allowed for 8 bit and 32 bit, can't remember the mechanism off the top of my head, but is it possible to extend this to 16 bit?

**Comment by rob-ng15** [comment]
It'll just make things easier for me, I can just point directly to the
compiled BIOS libraries, rather than have to convert them.

**Comment by sylefeb** [comment]
Hi Rob, from the source code I just realized uint16/int16 are already supported! Sorry I forgot to document it, fixing.

**Comment by rob-ng15** [comment]
Closing as working. Thank you.
