### ISSUE TITLE
circuitry calls only accept base identifiers

### ISSUE THREAD

**Issue by sylefeb** [sylefeb/Silice#34]
Allow at least 'access' (table, io, etc.) for inputs.

**Comment by rob-ng15** [comment]
( bitmap_x_write, bitmap_y_write, bitmap_write ) = writePixel( GPUrectangle.bitmap_x_write, GPUrectangle.bitmap_y_write, GPUrectangle.bitmap_write)

Where bitmap_* are outputs to an algorithm for the circuitry to write to, and GPUrectangle.* are outputs from an algorithm would greatly increase the flexibility of circuitry.

If there are technical reasons why this functionality cannot be added then I apologise for the request.

For intended use, please see [](url) https://github.com/rob-ng15/Silice-Playground/blob/master/risc-ice-v/gpu.ice starting from line 177, the section with each of the while loops in each of the case blocks would be perfect candidates to be replaced by the above type of circuitry.

Rob.

**Comment by rob-ng15** [comment]
Additional request if possible, allowing selection from a table as an input to the circuitry, either with a fixed selector, i.e. X[1] or a variable selector, i.e. X[y] would allow some useful optimisations.

**Comment by rob-ng15** [comment]
Further to the above, pass a constant to a circuit could be useful, appreciate that it may have to be a defined size...

e.g. N = 8; T = 0; ( result ) = CRC32( sourceReg1, N, T ); being replaced with ( result ) = CRC32( sourceReg1, 8h8, 8h0 );

**Comment by sylefeb** [comment]
At long last, this issue is fixed in a recent commit (as part of some larger ongoing changes).
