### ISSUE TITLE
Properly deallocate dynamically allocated resources

### ISSUE THREAD

**Issue by elfring** [sylefeb/Silice#44]
I have noticed that [the function call “`free(texinfo)`”](https://github.com/sylefeb/Silice/blob/9817a251d8eb1a0dea8fad74b5c2da2448e7d904/src/tga.cpp#L438 "Update candidate: ReadTGAFile()") was performed for an object which was created by the operator “`new`”.
Please [avoid undefined behavior](https://wiki.sei.cmu.edu/confluence/display/cplusplus/MEM51-CPP.+Properly+deallocate+dynamically+allocated+resources#MEM51-CPP.Properlydeallocatedynamicallyallocatedresources-NoncompliantCodeExample%28new%29 "Properly deallocate dynamically allocated resources").

**Comment by sylefeb** [comment]
Thanks - fixed already in branch wip, not yet push-ed.
