### ISSUE TITLE
Lua scripts and filesystem case insensitivity

### ISSUE THREAD

**Issue by diadatp** [sylefeb/Silice#58]
At least one of the Lua scripts (pre_do_textures.lua) has issues functioning on filesystems that are case sensitive. Running Silice (commit a5ef084) on the doomchip results in an error like the one below:

**[preprocessor] 16]  ../../doomchip/lumps/patches/w94_1.lump: No such file or directory**

The required lump can be found under the name W94_1.lump. A pull request #57 has been made to fix this issue.

**Comment by sylefeb** [comment]
Thanks - I merged the PR.
